### ISSUE TITLE
Jobs pagination in Scheduler web portal is broken

### ISSUE THREAD

**Issue by lpellegr** [ow2-proactive/scheduling-portal#251]
Jobs pagination is broken in Scheduler web interface. Lets say I have _190977_ jobs in _pending_ state in the scheduler. I set _Jobs page size_ to 5. Then, the first page displays _5_ jobs but when I click on _Next_ button I get _10_ jobs. Besides, the _Next_ button is disabled after first click, thus preventing users to see next page.

The issue occurs whatever the configuration is: even with default _Jobs page size_ the problem appears.

Below are some screenshots:

![capture d ecran de 2015-11-03 14-50-35](https://cloud.githubusercontent.com/assets/128898/10909555/5d9b1f9e-823a-11e5-9c78-48a62fdb00f8.png)

![capture d ecran de 2015-11-03 14-50-47](https://cloud.githubusercontent.com/assets/128898/10909561/60f5ebe2-823a-11e5-8026-6726731ee721.png)

**Comment by lpellegr** [comment]
Could be related with #243 also. I forgot to mention that the issue occurs with current master.

**Comment by sandrineBeauche** [comment]
It is not really a bug, the jobs pagination has been implemented in this way before I started working with scheduling-portal because the rest API does not gives the total number of jobs. So I see it as a "workaround" from the previous authors .

It should be fix with the next commits with task-centric, as I unified pagination for tasks and jobs, and Paraita is going to add total number of jobs in the json returned by the REST api.

**Comment by lpellegr** [comment]
@sandrineBeauche I am not sure to understand what you said. Jobs pagination is working with _6.3.0_ (e.g. you can test with try [1]). The problem is with 7.0.0-RC1 and current master only.

[1] https://try.activeeon.com/scheduler/

**Comment by sandrineBeauche** [comment]
No It worked like this when I started to work on task pagination. When I took a look how works the job pagination to do the same thing for tasks pagination, I was surprised that it works without the total number of jobs. And then I discovered the trick: it allows to go next page if the current page is full. And then if the next page is empty, next button is disabled.

**Comment by sandrineBeauche** [comment]
When the last page is not full, it detects that there is no more pages, so ok it works. I removed on try the 3 first jobs in order to have the number of jobs divisible by 5 for a page of 5 jobs/ So the last page is full. Now the last page is an empty page.

**Comment by sandrineBeauche** [comment]
fixed in commit 732a56deebc2e30fe09fb9d48753fa1cbbbf6a8f

**Comment by lpellegr** [comment]
Number of pages is now ok but it seems there is still an issue with the number of jobs displayed per page. I have opened #260.
